# Insights of the Cleaned Estate dataset

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sympy as sp

In [2]:
Estate_Data = pd.read_csv('cleaned_Estate.csv')

In [3]:
# Keep only rows where the price is greater than a reasonable minimum
Estate_Data = Estate_Data[Estate_Data['price'] > 1000]

In [4]:
"We basically did this because when we finded the answer of the problem with Top 10 cheapest cities with cheapest median houses we found out that there were houses with 0 dollar vlaue so we did before finding the answer of the quetion"

'We basically did this because when we finded the answer of the problem with Top 10 cheapest cities with cheapest median houses we found out that there were houses with 0 dollar vlaue so we did before finding the answer of the quetion'

In [5]:
Estate_Data

,Unnamed: 0,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,has_been_sold
0,0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,1
1,1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,1
2,2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,0
3,3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,1
4,4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92813,99995,78553.0,for_sale,249900.0,2.0,2.0,13.51,1876588.0,Sylva,North Carolina,28779.0,929.0,0
92814,99996,23001.0,sold,58000.0,2.0,1.0,0.16,663594.0,Streator,Illinois,61364.0,1050.0,1
92815,99997,81218.0,sold,124900.0,6.0,2.0,0.23,1774478.0,North Adams,Massachusetts,1247.0,1809.0,1
92816,99998,78465.0,sold,590000.0,4.0,4.0,0.20,1035102.0,Flower Mound,Texas,75022.0,3418.0,1
92817,99999,52776.0,for_sale,1050000.0,3.0,3.0,0.13,1820578.0,Denver,Colorado,80206.0,2276.0,1

In [6]:
Estate_Data.head()

,Unnamed: 0,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,has_been_sold
0,0,54239.0,sold,275000.0,1.0,1.0,0.70,1617038.0,Miami,Florida,33156.0,846.0,1
1,1,90564.0,sold,399900.0,1.0,1.0,6.20,1497499.0,San Diego,California,92108.0,667.0,1
2,2,53271.0,for_sale,75000.0,2.5,2.0,2.25,1877529.0,Oceola Township,Michigan,48855.0,1697.5,0
3,3,12926.0,sold,325000.0,3.0,2.0,0.09,892999.0,Worcester,Massachusetts,1603.0,1409.0,1
4,4,79221.0,for_sale,169900.0,3.5,3.0,3.70,1998116.0,Holmen,Wisconsin,54636.0,2875.0,0

In [7]:
#The most expensive area to buy the houses 
top_10_cities = Estate_Data.groupby('city')['price'].median().sort_values(ascending = False).head(10)

In [8]:
print(f'THE TOP 10 cities with most expensive houses\n{top_10_cities}')

THE TOP 10 cities with most expensive houses
city
Aspen            49500000.0
Gulf Stream      30000000.0
Pebble Beach     29750000.0
Micanopy         14137500.0
Congress         12868550.0
Whitesville      12799950.0
Bridgehampton    12495000.0
Telluride        11299500.0
Amagansett       11247500.0
Locust Valley    10957500.0
Name: price, dtype: float64

In [9]:
"we are using the  median here because we want to find the median value so that if we use the mean  then some property like 100m$ can't inflate the data "

"we are using the  median here because we want to find the median value so that if we use the mean  then some property like 100m$ can't inflate the data "

In [10]:
#the top 10 cities with lowest median houses prices 
Low_10_cities = Estate_Data.groupby('city')['price'].median().sort_values(ascending = True).head(10)

In [11]:
print(f"The Top 10 cities with cheapest median houses\n{Low_10_cities}")

The Top 10 cities with cheapest median houses
city
Rio del Oro Los Lunas    1500.0
Redbird                  2000.0
Fairfield Bay            2500.0
Penn Forest Township     5000.0
Lake Summerset           5250.0
Dr Unit 78 Deming        5900.0
Four Seasons             6500.0
Heidelberg               6500.0
Ottoman                  6900.0
Lake Sherwood            7000.0
Name: price, dtype: float64

In [12]:
#finding median prices for per sqaure foot basically mean area of prices per feet  in data set

In [13]:
Estate_Data['price_per_sqft'] = Estate_Data['price']/Estate_Data['house_size']

In [14]:
import math 
#finding the median for price per square feet 
Median_psft = math.ceil(Estate_Data['price_per_sqft'].median())

In [15]:
import math 
print(f'The Median of the price per sqrft of the area in this dataset is {Median_psft}')

The Median of the price per sqrft of the area in this dataset is 183

In [22]:
#how much the price of the property increse when we increase the number of the bedrooms 
bed_increase = Estate_Data.groupby('bed')[['price','house_size']].median().sort_index()

In [23]:
bed_increase

           price  house_size
bed
1.0     249900.0       771.0
1.5      79900.0      1116.0
2.0     259900.0      1190.0
2.5      99000.0      1425.5
3.0     289900.0      1662.0
3.5      90000.0      2053.0
4.0     430000.0      2321.0
4.5     110000.0      2776.0
5.0     620000.0      3096.0
5.5      65000.0      3290.0
6.0     687000.0      3418.0
6.5      99000.0      2288.0
7.0    1184500.0      4075.5
7.5      99900.0      3261.0
8.0     822500.0      3720.5
9.0     762500.0      4045.0
9.5     159900.0      4966.0
10.0    712500.0      4601.5
10.5     29900.0      3798.0
11.0    799975.0      3710.5
12.0    975000.0      4630.0
13.0   1200000.0      5970.0
14.0    650000.0      4525.0
15.0   1799000.0      5982.0
16.0   1200000.0      6336.0
17.0  48000000.0     19741.0
18.0   1699500.0      9309.0
19.0   2750000.0      7784.0
20.0   1125000.0      9770.5
21.0    925000.0      8888.0
22.0   1999000.0      9983.0
23.0   1114950.0      8536.5
24.0   5190000.0     12704.0
25.0   4195000.0     11921.0
27.0   3732995.0     14664.5
28.0   4200000.0     11340.0
29.0   1650000.0     12728.0
31.0   7500000.0     22774.0
32.0   1295000.0     13144.0
33.0   1250000.0     24174.0
35.0   3900000.0     19922.0
36.0   6365000.0     29328.5
40.0   5199500.0     10789.5
41.0   2900000.0     16503.0
42.0   2492000.0     15500.0
48.0   1520000.0      1512.0
49.0   9200000.0     23360.0
62.0  11300000.0     30266.0
66.0     49900.0     17660.0
74.0   3215625.0     45580.0
99.0   5300000.0     14462.0

In [24]:
#so now we can also find the which states have most active sale market like which state have more more percentage to the ratio of there house sale 
#so here we are calculating percentage because of number of the houses cities are different and other measure

In [75]:
market_percentage = Estate_Data.groupby('state')['status'].value_counts(normalize = True)*100
market_percentage

state      status
Alabama    for_sale           75.800712
           sold               21.209964
           ready_to_build      2.989324
Alaska     for_sale          100.000000
Arizona    for_sale           49.621928
                                ...
Wisconsin  for_sale           57.038391
           sold               42.900670
           ready_to_build      0.060938
Wyoming    for_sale           99.285714
           sold                0.714286
Name: proportion, Length: 138, dtype: float64

In [76]:
active_market = market_percentage.loc[:,'for_sale'].sort_values(ascending=False)

In [78]:
print(f'The Top State with highest percentage of the active market it :\n{active_market.head(10)}')

The Top State with highest percentage of the active market it :
state
Guam             100.000000
Alaska           100.000000
North Dakota     100.000000
Vermont          100.000000
Wyoming           99.285714
Maine             99.275362
Connecticut       99.142367
New Hampshire     98.387097
South Dakota      97.402597
Indiana           96.765847
Name: proportion, dtype: float64

In [79]:
"so here comes the problem that data in the data maybe there is hoow with 1 house for sale and nothing sold then we have to think about the bias to think about we have to set limit atleast every entry should have atleast 500 of house for sale and sold as totle"

'so here comes the problem that data in the data maybe there is hoow with 1 house for sale and nothing sold then we have to think about the bias to think about we have to set limit atleast every entry should have atleast 500 of house for sale and sold as totle'

In [83]:
#solution 
state_summary = Estate_Data.groupby('state')['status'].agg(
    total_listing = 'count',
    percentage_for_sale  = lambda s: (s=='for_sale').mean()*100
    )#calculate the count of the data and the percentage on the data we have done the multiple math so we choose aggregation here 
reliable_market = state_summary[state_summary['total_listing']>=100]
active_reliable_market = reliable_market.sort_values(by='percentage_for_sale',ascending = False).head(10)

In [84]:
print(f'The Top State with highest percentage of the active market it :\n{active_reliable_market.head(10)}')

The Top State with highest percentage of the active market it :
               total_listing  percentage_for_sale
state
Vermont                  112           100.000000
North Dakota             151           100.000000
Wyoming                  140            99.285714
Maine                    138            99.275362
Connecticut              583            99.142367
New Hampshire            124            98.387097
South Dakota             154            97.402597
Indiana                  773            96.765847
Nebraska                 246            96.747967
Hawaii                   310            94.516129